#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 22 14:49:11 2021

@author: yamamotod
"""


#вар1 
with open('nginx_logs.txt', encoding='utf-8') as f:
   #print(type(f))
   ls = ((re.split(' ',l)[0],re.split(' ',l)[5][1:],re.split(' ',l)[6]) for l in f)
   print(*ls)  
# 
#вар2
with open('nginx_logs.txt', encoding='utf-8') as f:
   #print(type(f))
   ls = (map(lambda l:l.split(' ')[0],l.split(' ')[5][1:],l.split(' ')[6]) for l in f)
   item = [item for item in ls]
   print(item) 